calculibrium/urls.py
from django.urls import path

from . import views

app_name = 'calculibrium'
urlpatterns = [
    path("", views.index, name="index"),
    path("change_theme/", views.change_theme, name="change_theme"),
    path("<str:categoria_componente>/list", views.list, name="list"),
    path("<str:categoria_componente>/select", views.select, name="select"),

    path("inverter", views.inverter, name="inverter"),
    path("cable/ac", views.cable_ac, name="cable_ac"),

    path("roof_disponibilization", views.roof_disponibilization, name="roof_disponibilization"),
    path("structure/kwp", views.structure_kwp, name="structure_kwp"),
    path("structure/un", views.structure_un, name="structure_un"),
    
    path("find-cable-ac/<current_max>/<distance>/<int:connection_type>", views.find_cable_ac, name="find_cable_ac"),
    path("find-circuit-breaker/<current>/<int:connection_type>", views.find_circuit_breaker, name="find_circuit_breaker"),
    path("find-modules-amount/<int:module_pk>/<power_plant>", views.find_modules_amount, name="find_modules_amount"),
    path("find-inverters/<power_plant>", views.find_inverters, name="find_inverters"),
]

vercel_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculibrium.urls')),
]

# add at the last
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

calculibrium/views.py
import json
import math
import requests
from django.db.models import F, Max
from django.forms.models import model_to_dict
from django.http import Http404, JsonResponse
from django.core.handlers.wsgi import WSGIRequest
from django.core import serializers
from django.core.exceptions import FieldError
from django.shortcuts import get_object_or_404, render
from calculibrium.model.power_plant import PowerPlant
from calculibrium.model.roof import Roof
from calculibrium.model.inverter import get_cheaper
from .models import *

def index(request: WSGIRequest):
    return render(request, "calculibrium/index.html")

def change_theme(request: WSGIRequest):
    theme = request.session.get('theme', 'light')
    if theme == 'light':
        request.session['theme'] = 'dark'
    else:
        request.session['theme'] = 'light'
    return JsonResponse({'success': True})

def list(request: WSGIRequest, categoria_componente):
    try:
        list = DBComponent.objects.filter(categoria_componente__exact=categoria_componente)
    except DBComponent.DoesNotExist:
        raise Http404('Component does not exist!')
    return render(request, "calculibrium/list.html", {"list": list})

def cable_ac(request: WSGIRequest):
    inversores = DBInverter.objects.all()
    marcas = DBBrand.objects.filter(dbinverter__in=inversores).distinct()
    marcas_json = serializers.serialize('json', marcas)
    inversores_json = serializers.serialize('json', inversores)

    if request.method == 'POST':
        inverters = []
        circuit_breakers = []
        cables = []
        inverters_pk = request.POST.getlist('component')
        inverters_amount = [int(x) for x in request.POST.getlist('txt_inverter_amount')]
        distance = float(request.POST.get('txt_distance'))
        current = 0

        for index, (pk, amount) in enumerate(zip(inverters_pk, inverters_amount)):
            inv = get_object_or_404(DBInverter, pk=pk)
            current += inv.ca_current*amount

            response = find_circuit_breaker(request, inv.ca_current, inv.connection_type)
            if response.status_code == 200:
                circuit_breaker = json.loads(response.content.decode('utf-8'))['disjuntor']
            else:
                return response

            distance_request = distance if sum(inverters_amount) == 1 else 15

            response = find_cable_ac(request, circuit_breaker['current'], distance_request, inv.connection_type)
            if response.status_code == 200:
                data = json.loads(response.content.decode('utf-8'))
                cable_ac_pt = data['model_pt']
                cable_ac_az = data['model_az']
                cable_ac_vd = data['model_vd']
                distance_pt = data['distance_pt']
                distance_az = data['distance_az']
                distance_vd = data['distance_vd']
            else:
                return response

            inverters.append(['175XXXX', str(inv.model)+' - '+ str(inv.ca_current) + ' A', amount])
            circuit_breakers.append(['150XXXX', str(circuit_breaker['description'])+' - '+str(circuit_breaker['current'])+ ' A', amount])
            cables.append(['217XXXX', cable_ac_pt['description']+' preto - '+ str(cable_ac_pt['current']) + ' A', distance_pt*amount])
            cables.append(['217XXXX', cable_ac_az['description']+' azul - '+ str(cable_ac_az['current']) + ' A', distance_az*amount])
            cables.append(['217XXXX', cable_ac_vd['description']+' verde - '+ str(cable_ac_vd['current']) + ' A', distance_vd*amount])
        else:
            if sum(inverters_amount) > 1:
                response = find_circuit_breaker(request, current, inv.connection_type)
                if response.status_code == 200:
                    circuit_breaker = json.loads(response.content.decode('utf-8'))['disjuntor']
                else:
                    return response

                response = find_cable_ac(request, circuit_breaker['current'], distance, inv.connection_type)
                if response.status_code == 200:
                    data = json.loads(response.content.decode('utf-8'))
                    cable_ac_pt = data['model_pt']
                    distance_pt = data['distance_pt']
                    cable_ac_az = data['model_az']
                    distance_az = data['distance_az']
                    cable_ac_vd = data['model_vd']
                    distance_vd = data['distance_vd']
                else:
                    return response
                circuit_breakers.append(['150XXXX', str(circuit_breaker['description'])+' - '+str(circuit_breaker['current'])+ ' A', 1])
                cables.append(['217XXXX', cable_ac_pt['description']+' preto - '+ str(cable_ac_pt['current']) + ' A', distance_pt])
                cables.append(['217XXXX', cable_ac_az['description']+' azul - '+ str(cable_ac_az['current']) + ' A', distance_az])
                cables.append(['217XXXX', cable_ac_vd['description']+' verde - '+ str(cable_ac_vd['current']) + ' A', distance_vd])
        return render(request, 'calculibrium/cable_ac.html', {
            'inverters': inverters,
            'circuit_breakers': circuit_breakers,
            'cables': cables,
            'marcas_json': marcas_json,
            'inversores_json': inversores_json,
            'distance': distance
            })
    else:
        return render(request, 'calculibrium/cable_ac.html', {'marcas_json': marcas_json, 'inversores_json': inversores_json})

def select(request: WSGIRequest, categoria_componente):
    componentes = DBComponent.objects.filter(categoria_componente=categoria_componente)
    marcas = DBBrand.objects.filter(dbcomponent__in=componentes).distinct()
    marcas_json = serializers.serialize('json', marcas)
    componentes_json = serializers.serialize('json', componentes)
    if request.method == 'POST':
        print(request.POST.getlist('container-inverters'))
    return render(request, 'calculibrium/select_component.html', {'marcas_json': marcas_json, 'componentes_json': componentes_json})

def inverter(request: WSGIRequest):
    componentes = DBComponent.objects.filter(categoria_componente='IN')
    marcas = DBBrand.objects.filter(dbcomponent__in=componentes).distinct()
    marcas_json = serializers.serialize('json', marcas)
    componentes_json = serializers.serialize('json', componentes)
    return render(request, 'calculibrium/inverter.html',
                  {
                      'marcas_json': marcas_json,
                      'componentes_json': componentes_json,
                  })

def roof_disponibilization(request: WSGIRequest):
    roof = Roof(DBComponent.objects.get(cdcrm=1750512), 93)
    return render(request, "calculibrium/index.html")

def structure_kwp(request: WSGIRequest):
    componentes = DBComponent.objects.filter(categoria_componente='PN', largura__gt=0)
    marcas = DBBrand.objects.filter(dbcomponent__in=componentes).distinct()
    marcas_json = serializers.serialize('json', marcas)
    componentes_json = serializers.serialize('json', componentes)
    power_plant = PowerPlant('Rafael Chang', DBComponent.objects.get(cdcrm=1750512), 103.68)
    if request.method == 'POST':
        items = {}
        for chave, valor in request.POST.items():
            items[chave] = valor
        module = DBComponent.objects.get(pk=items['slcModuleModel'])
        power_plant = PowerPlant(items['txt_customers_name'], 
                                 module,
                                 float(items['txt_power_plant_power']))
        # power_plant.inverter_table = True if items['chk_inverter'] else False
        power_plant.inverter_table = True if request.POST.get('chk_inverter') else False
        power_plant.calc_structure()
        power_plant.calc_concrete(1.6, 0.15, 0.4, 0.2)
    return render(request, "calculibrium/structure_kwp.html", 
                  {
                    "power_plant": power_plant,
                    "grounding": power_plant.table.grounding,
                    'brands': marcas_json,
                    'components': componentes_json,
                   })

def structure_un(request: WSGIRequest):
    componentes = DBComponent.objects.filter(categoria_componente='PN', largura__gt=0)
    marcas = DBBrand.objects.filter(dbcomponent__in=componentes).distinct()
    marcas_json = serializers.serialize('json', marcas)
    componentes_json = serializers.serialize('json', componentes)
    power_plant = PowerPlant('Rafael Chang', DBComponent.objects.get(cdcrm=1750512), 0)
    if request.method == 'POST':
        items = {}
        for chave, valor in request.POST.items():
            items[chave] = valor
        try:
            modules_amount = [int(i) for i in request.POST.getlist('txt_modules_amount')]
            tables_amount = [int(i) for i in request.POST.getlist('txt_tables_amount')]
        except:
            raise FieldError('Calculo não realizado, verifique os campos e tente novamente!')
        module = DBComponent.objects.get(pk=items['slcModuleModel'])
        power_plant = PowerPlant(items['txt_customers_name'], 
                                 module,
                                 0)
        power_plant.modules_amount = sum([int(i)*int(tables_amount[idx]) for idx, i in enumerate(modules_amount)])
        power_plant.real_power = power_plant.modules_amount*float(power_plant.module.potencia)/1e3
        power_plant.table.tables['qtd_modulo'] = modules_amount
        power_plant.table.tables['qtd_mesas'] = tables_amount
        power_plant.table.tables['dimensions'] = power_plant.table.calculate_dimensions(max(modules_amount), sum(tables_amount))
        power_plant.inverter_table = True if request.POST.get('chk_inverter') else False
        power_plant.table.calc_grounding()
        power_plant.calc_structure()
        power_plant.calc_concrete(1.6, 0.15, 0.4, 0.2)
        return render(request, "calculibrium/structure_un.html", {
            "power_plant": power_plant,
            "grounding": power_plant.table.grounding,  

calculibrium/templates/calculibrium/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Calculibrium{% endblock title %}</title>
    {% block head %}{% endblock head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body data-bs-theme="{{ request.session.theme|default:'light' }}">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Calculibrium</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'calculibrium:index' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Comercial
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'calculibrium:structure_kwp' %}">Estrutura</a></li>
                  <li><a class="dropdown-item" href="{% url 'calculibrium:cable_ac' %}">Cabos AC</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Engenharia
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'calculibrium:structure_kwp' %}">Estrutura [kWp]</a></li>
                  <li><a class="dropdown-item" href="{% url 'calculibrium:structure_un' %}">Estrutura [Un]</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Memorial de Calculo</a>
              </li>
            </ul>
            <ul>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" id="change-theme">Tema</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    {% block content %}
      
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
      document.getElementById('change-theme').addEventListener('click', function(){
        var url = '/change_theme/';
        var xhr = new XMLHttpRequest();
        xhr.open('GET', url, true);
        xhr.onreadystatechange = function(){
          if (xhr.readyState == 4 && xhr.status == 200){
            var response = JSON.parse(xhr.responseText);
            if (response.success){
              alert('Theme changed successfully!');
              location.reload();
            }
          }
        };
        xhr.send();
      });
    </script>
</body>
</html>

calculibrium/templates/calculibrium/cable_ac.html
{% extends "calculibrium/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <h3 class="card-header">Entenda os Cálculos</h3>
        <div class="card-body">
          <p>Este campo é realizado o dimensionamento dos disjuntores e dos cabos CA, seguindo as seguintes premissas:</p>
    
          <ul>
            <li>O disjuntor deve ser dimensionado para suportar a corrente máxima do inversor;</li>
            <li>O disjuntor deve ser dimensionado para acionar antes da corrente máxima que o cabo suporta;</li>
            <li>A partir da bitola de 50 mm², por lei, o dimensionamento dos cabos neutro e terra podem ser considerados a metade da bitola das fases.</li>
            <li>A maior bitola considerada é de 240 mm², a partir da corrente que o cabo suporta é considerado mais de um cabo por fase.</li>
          </ul>
        
          <p>Estas considerações são fundamentais para garantir a estabilidade e eficiência da usina.</p>
        
        </div>
    </div>
    <form method="post">
    {% csrf_token %}
        <div class="card">
            <h3 class="card-header">Entradas</h3>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <label class="form-label">Selecione os Inversores</label>
                        <div class="container" name="container-inverters" id="linhas-container">
                        </div>
                    </div>
                    <div class="row" style="width: 99%;">
                        <div class="mb-3">
                            <label for="txt_distance" class="form-label">Distância Ponto de Conexão</label>
                            <input type="number" step="1" class="form-control" name="txt_distance" id="txt_distance" value="{{distance}}">
                            <div id="lbl_height_buried" class="form-text">Insira a distância até o ponto de Conexão.</div>
                        </div>
                    </div>
                    <div class="row" style="width: 97%; margin-left: 1px;">
                        <button type="submit" name="calculate" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </div>
        {% if inverters %}
        <div class="card">
            <h3 class="card-header">Saída</h3>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Código</th>
                            <th scope="col">Descrição</th>
                            <th scope="col">Quantidade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inverter in inverters %}
                            <tr>
                                <td>{{inverter.0}}</td>
                                <td>{{inverter.1}}</td>
                                <td>{{inverter.2}}</td>
                            </tr>
                        {% endfor %}
                        {% for circuit_breaker in circuit_breakers %}
                            <tr>
                                <td>{{circuit_breaker.0}}</td>
                                <td>{{circuit_breaker.1}}</td>
                                <td>{{circuit_breaker.2}}</td>
                            </tr>
                        {% endfor %}
                        {% for cable in cables %}
                            <tr>
                                <td>{{cable.0}}</td>
                                <td>{{cable.1}}</td>
                                <td>{{cable.2}}</td>
                            </tr>
                        {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </form>
</div>

<script>
    const marcas = JSON.parse('{{marcas_json | escapejs }}');
    const linhasContainer = document.getElementById('linhas-container');
    const inversores = JSON.parse('{{inversores_json | escapejs }}');

    function adicionarLinha(btn_add_rem){

        const divInverters = document.createElement('div');
        divInverters.className = 'inversores';
        divInverters.setAttribute('name', 'inversores');
        const divRow = document.createElement('div');
        divRow.className = 'row';
        const divColBrand = document.createElement('div');
        divColBrand.className = 'col';
        const divColComponent = document.createElement('div');
        divColComponent.className = 'col';
        const divColAmount = document.createElement('div');
        divColAmount.className = 'col-sm-1';
        const marcaSelect = document.createElement('select');
        marcaSelect.className = 'form-select form-select-lg mb-3';
        marcaSelect.setAttribute('name', 'marca');
        const componentSelect = document.createElement('select');
        componentSelect.className = 'form-select form-select-lg mb-3';
        componentSelect.setAttribute('name', 'component');

        const divInputAmount = document.createElement('div');
        divInputAmount.className = 'mb-2';
        divInputAmount.innerHTML = `<input type="number" step="1" class="form-control form-control-for-select" name="txt_inverter_amount" id="txt_inverter_amount" value="1">`;

        const divColBtn = document.createElement('div');
        divColBtn.className = 'col-sm-1';
        console.log(btn_add_rem);
        if(btn_add_rem == 'add'){
            divColBtn.innerHTML = '<button type="button" id="adicionar-linha" class="btn btn-outline-success btn-lg">+</button>';
        }else{
            divColBtn.innerHTML = '<button type="button" id="remover-linha" class="btn btn-outline-danger btn-lg">-</button>';
        }

        marcaSelect.innerHTML = '<option value="" selected>Selecione uma marca</option>';
        marcas.forEach(marca => {
            const option = document.createElement('option');
            option.text = marca.fields.name;
            option.value = marca.pk;
            marcaSelect.add(option)
        });

        marcaSelect.addEventListener('blur', function() {
            const marcaSelecionada = this.value;
            componentSelect.innerHTML = '<option value="" selected>Selecione um componente</option>';
            inversores.forEach(componente => {
                console.log('brand: ', componente.fields.brand, '; marca: ', marcaSelecionada)
                if(componente.fields.brand == marcaSelecionada){
                    var option = document.createElement('option');
                    option.text = componente.fields.model;
                    option.value = componente.pk
                    componentSelect.appendChild(option)
                }
            });
        });
        divColBrand.appendChild(marcaSelect);
        divColComponent.appendChild(componentSelect);
        divColAmount.appendChild(divInputAmount);
        divRow.appendChild(divColBrand);
        divRow.appendChild(divColComponent);
        divRow.appendChild(divColAmount);
        divRow.appendChild(divColBtn);
        divInverters.appendChild(divRow);
        linhasContainer.appendChild(divInverters);
    }
    adicionarLinha('add');
    linhasContainer.addEventListener('click', function(event) {
        if (event.target.id === 'remover-linha') {
            var linhaRemovida = event.target.closest('.inversores');
            linhaRemovida.remove();
        }
    });
    document.getElementById('adicionar-linha').addEventListener('click', adicionarLinha);
    
</script>

{% endblock content %}

calculibrium/templates/calculibrium/index.html
{% extends "calculibrium/base.html" %}

{% block title %}
  Home
{% endblock title %}

{% block content %}
<div class="container">
    <div class="card">
        <h3 class="card-header">Comercial</h3>
        <div class="card-body">
            <dl>
                <dt>Estrutura</dt>
                <dd>Calcula os componentes utilizados na estrutura pela potência da usina em kWp, arranjo das mesas é otimizado</dd>
            </dl>
        </div>
    </div>
    <div class="card">
        <h3 class="card-header">Engenharia</h3>
        <div class="card-body">
            <dl>
                <dt>Estrutura [kWp]</dt>
                <dd>Calcula os componentes utilizados na estrutura pela potência da usina em kWp, arranjo das mesas é otimizado</dd>
                <dt>Estrutura [un]</dt>
                <dd>Calcula os componentes utilizados na estrutura pelo arranjo de mesas</dd>
            </dl>
        </div>
    </div>
</div>
{% endblock content %}

calculibrium/templates/calculibrium/inverter.html
{% extends "calculibrium/base.html" %}
{% load calculibrium_extras %}
{% block title %}
  Calculo de Disjuntores e Cabos AC
{% endblock title %}

{% block content %}
<div class="container">
    <div class="card" style="width: 90%;">
        <br>
        <div class="container" name="container-inverters" id="linhas-container">
        </div>
    </div>
</div>
<script>
    const marcas = JSON.parse('{{marcas_json | escapejs }}');
    const linhasContainer = document.getElementById('linhas-container');
    const componentes = JSON.parse('{{componentes_json | escapejs }}');

    function adicionarLinha(btn_add_rem){
        const divInverters = document.createElement('div');
        divInverters.className = 'inversores';
        const divRow = document.createElement('div');
        divRow.className = 'row';
        const divColBrand = document.createElement('div');
        divColBrand.className = 'col';
        const divColComponent = document.createElement('div');
        divColComponent.className = 'col';
        const marcaSelect = document.createElement('select');
        marcaSelect.className = 'form-select form-select-lg mb-3';
        const componentSelect = document.createElement('select');
        componentSelect.className = 'form-select form-select-lg mb-3';
        const divColBtn = document.createElement('div');
        divColBtn.className = 'col-sm-1';
        console.log(btn_add_rem);
        if(btn_add_rem == 'add'){
            divColBtn.innerHTML = '<button type="button" id="adicionar-linha" class="btn btn-outline-success btn-lg">+</button>';
        }else{
            divColBtn.innerHTML = '<button type="button" id="remover-linha" class="btn btn-outline-danger btn-lg">-</button>';
        }

        marcaSelect.innerHTML = '<option value="" selected>Selecione uma marca</option>';
        marcas.forEach(marca => {
            const option = document.createElement('option');
            option.text = marca.fields.name;
            option.value = marca.pk;
            marcaSelect.add(option)
        });

        marcaSelect.addEventListener('change', function() {
            const marcaSelecionada = this.value;
            componentSelect.innerHTML = '<option value="" selected>Selecione um componente</option>';
            componentes.forEach(componente => {
                console.log('brand: ', componente.fields.brand, '; marca: ', marcaSelecionada)
                if(componente.fields.brand == marcaSelecionada){
                    var option = document.createElement('option');
                    option.text = componente.fields.descricao;
                    option.value = componente.pk
                    componentSelect.appendChild(option)
                }
            });
        });
        divColBrand.appendChild(marcaSelect);
        divColComponent.appendChild(componentSelect);
        divRow.appendChild(divColBrand);
        divRow.appendChild(divColComponent);
        divRow.appendChild(divColBtn);
        divInverters.appendChild(divRow);
        linhasContainer.appendChild(divInverters);
    }
    adicionarLinha('add');
    linhasContainer.addEventListener('click', function(event) {
        if (event.target.id === 'remover-linha') {
            var linhaRemovida = event.target.closest('.inversores');
            linhaRemovida.remove();
        }
    });
    document.getElementById('adicionar-linha').addEventListener('click', adicionarLinha);
    
</script>
{% endblock content %}

calculibrium/templates/calculibrium/list.html
{% extends "calculibrium/base.html" %}

{% block title %}
  Lista de 
{% endblock title %}

{% block content %}
<center>
    <div class="card" style="width: 70%;">
        <ul class="list-group list-group-flush">
            {% for item in list %}
                <li class="list-group-item">{{item.cdcrm}} - {{item}}</li>
            {% endfor %}
            <!-- <li class="list-group-item">Componente 1</li>
            <li class="list-group-item">Componente 2</li>
            <li class="list-group-item">Componente 3</li>
            <li class="list-group-item">Componente 4</li> -->
        </ul>
    </div>
</center>
{% endblock content %}

calculibrium/templates/calculibrium/select_component.html
{% extends "calculibrium/base.html" %}
{% block content %}
<div class="container">
    <div class="card" style="width: 90%;">
        <br>
        <div class="container" name="container-inverters" id="linhas-container">
        </div>
    </div>
</div>
<script>
    const marcas = JSON.parse('{{marcas_json | escapejs }}');
    const linhasContainer = document.getElementById('linhas-container');
    const componentes = JSON.parse('{{componentes_json | escapejs }}');

    function adicionarLinha(btn_add_rem){
        const divInverters = document.createElement('div');
        divInverters.className = 'inversores';
        const divRow = document.createElement('div');
        divRow.className = 'row';
        const divColBrand = document.createElement('div');
        divColBrand.className = 'col';
        const divColComponent = document.createElement('div');
        divColComponent.className = 'col';
        const marcaSelect = document.createElement('select');
        marcaSelect.className = 'form-select form-select-lg mb-3';
        const componentSelect = document.createElement('select');
        componentSelect.className = 'form-select form-select-lg mb-3';
        const divColBtn = document.createElement('div');
        divColBtn.className = 'col-sm-1';
        console.log(btn_add_rem);
        if(btn_add_rem == 'add'){
            divColBtn.innerHTML = '<button type="button" id="adicionar-linha" class="btn btn-outline-success btn-lg">+</button>';
        }else{
            divColBtn.innerHTML = '<button type="button" id="remover-linha" class="btn btn-outline-danger btn-lg">-</button>';
        }

        marcaSelect.innerHTML = '<option value="" selected>Selecione uma marca</option>';
        marcas.forEach(marca => {
            const option = document.createElement('option');
            option.text = marca.fields.name;
            option.value = marca.pk;
            marcaSelect.add(option)
        });

        marcaSelect.addEventListener('change', function() {
            const marcaSelecionada = this.value;
            componentSelect.innerHTML = '<option value="" selected>Selecione um componente</option>';
            componentes.forEach(componente => {
                console.log('brand: ', componente.fields.brand, '; marca: ', marcaSelecionada)
                if(componente.fields.brand == marcaSelecionada){
                    var option = document.createElement('option');
                    option.text = componente.fields.descricao;
                    option.value = componente.pk
                    componentSelect.appendChild(option)
                }
            });
        });
        divColBrand.appendChild(marcaSelect);
        divColComponent.appendChild(componentSelect);
        divRow.appendChild(divColBrand);
        divRow.appendChild(divColComponent);
        divRow.appendChild(divColBtn);
        divInverters.appendChild(divRow);
        linhasContainer.appendChild(divInverters);
    }
    adicionarLinha('add');
    linhasContainer.addEventListener('click', function(event) {
        if (event.target.id === 'remover-linha') {
            var linhaRemovida = event.target.closest('.inversores');
            linhaRemovida.remove();
        }
    });
    document.getElementById('adicionar-linha').addEventListener('click', adicionarLinha);
    
</script>

{% endblock content %}